version: "3.7"
services:
  ldap:
    image: osixia/openldap:1.4.0
    environment:
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_TLS=false
    ports:
      - 389
    volumes:
      - type: bind
        source: ./scaffolding/ldap
        target: /container/service/slapd/assets/config/bootstrap/ldif/custom/
    healthcheck:
      test: /usr/bin/ldapsearch -x -h localhost -b dc=example,dc=org cn=test,ou=users,dc=example,dc=org
    command: --loglevel debug --copy-service
  postgres:
    image: aweber/imbi-postgres:0.14.0
    ports:
      - 5432
    volumes:
      - ./scaffolding/postgres:/tmp/postgres
  redis:
    image: gavinmroy/alpine-redis:5.0.9-0
    ports:
      - 6379

  test-python3.9:
    image: python:3.9-alpine
    links:
      - ldap
      - postgres
      - redis
    volumes:
      - ./build:/tmp/test/build:rw
      - ./:/source:ro
    command: /source/ci/test.sh

  imbi:
    image: aweber/imbi:latest
    links:
      - ldap
      - postgres
      - redis
    ports:
      - 8000
    volumes:
      - ./docker-config.yaml:/etc/imbi/imbi.yaml
