disable_existing_loggers = false
incremental = false
version = 1

[formatters.readable]
format = "%(asctime)s.%(msecs)03d %(levelname)-12s %(name)s: %(message)s"
datefmt = "%Y-%m-%dT%H:%M:%S"

[handlers.console]
class = "logging.StreamHandler"
stream = "ext://sys.stdout"
formatter = "readable"

[loggers]
uvicorn = { level = "INFO" }

[root]
level = "INFO"
handlers = ["console"]
