name: Service Testing
on:
  push:
    branches: ["*"]
    paths:
      - 'imbi/**'
      - 'tests/**'
      - 'setup.*'
    tags-ignore: ["*"]
  pull_request:
    branches: ["*"]
    paths:
      - 'imbi/**'
      - 'tests/**'
      - 'setup.*'
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bootstrap environment
        run: make .env
      - name: Run Tests
        run: docker-compose run --rm -T test-python3.9
      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.2
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'aweber/imbi'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: build/coverage.xml
